### ISSUE TITLE
version is set to 1.7.1, but the repo at cloudbees stops at 1.6.2

### ISSUE THREAD

**Issue by elijah** [JustinAiken/openhab-cookbook#1]
attributes/default.rb defaults to package install - a vagrant up looks for packages at cloudbees and cant' find them, because the repo doesn't contain the right versions.

The install-from-packages recipe should have a conditional added around the repo setup to add the other repo at bintray... e.g. instructions from https://github.com/openhab/openhab/wiki/Linux---OS-X

**Comment by JustinAiken** [comment]
> the repo at cloudbees stops at 1.6.2

Ah bummer, that's inconvenient!  

If you want to file a PR to fix that, I'll accept/merge/push out a new version...

I probably won't fix it myself though, since I've actually moved to [using Docker](https://github.com/JustinAiken/rpi-openhab/) to set up openHAB..

**Comment by elijah** [comment]
I'll put a pull request in soon.

Thx,

--e

**Comment by elijah** [comment]
Pull request submitted.
